apiVersion: v1
kind: Service
metadata:
  name: mynodeproject
  namespace: mynodeproject-demo
spec:
  type: NodePort
  selector:
    app: mynodeproject
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30180
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mynodeproject
  namespace: mynodeproject-demo
spec:
  selector:
    matchLabels:
      app: mynodeproject
  replicas: 1
  template:
    metadata:
      labels:
        app: mynodeproject
    spec:
      containers:
      - name:mynodeproject
        image: 197149372921.dkr.ecr.ca-central-1.amazonaws.com/mynodeproject:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: aws-ecr
